In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('C:/Users/Pavel/Downloads/country_vaccinations.csv')


In [3]:
df.head()

country iso_code        date  total_vaccinations  people_vaccinated  \
0  Algeria      DZA  2021-01-29                 0.0                NaN   
1  Algeria      DZA  2021-01-30                30.0                NaN   
2  Andorra      AND  2021-01-25               576.0              576.0   
3  Andorra      AND  2021-01-26                 NaN                NaN   
4  Andorra      AND  2021-01-27                 NaN                NaN   

   people_fully_vaccinated  daily_vaccinations_raw  daily_vaccinations  \
0                      NaN                     NaN                 NaN   
1                      NaN                    30.0                30.0   
2                      NaN                     NaN                 NaN   
3                      NaN                     NaN                66.0   
4                      NaN                     NaN                66.0   

   total_vaccinations_per_hundred  people_vaccinated_per_hundred  \
0                            0.00                            NaN   
1                            0.00                            NaN   
2                            0.75                           0.75   
3                             NaN                            NaN   
4                             NaN                            NaN   

   people_fully_vaccinated_per_hundred  daily_vaccinations_per_million  \
0                                  NaN                             NaN   
1                                  NaN                             1.0   
2                                  NaN                             NaN   
3                                  NaN                           854.0   
4                                  NaN                           854.0   

          vaccines            source_name  \
0        Sputnik V     Ministry of Health   
1        Sputnik V     Ministry of Health   
2  Pfizer/BioNTech  Government of Andorra   
3  Pfizer/BioNTech  Government of Andorra   
4  Pfizer/BioNTech  Government of Andorra   

                                      source_website  
0  https://www.aps.dz/regions/116777-blida-covid-...  
1  https://www.aps.dz/regions/116777-blida-covid-...  
2  https://www.govern.ad/comunicats/item/12379-se...  
3  https://www.govern.ad/comunicats/item/12379-se...  
4  https://www.govern.ad/comunicats/item/12379-se...

In [4]:
df.tail()

country iso_code        date  total_vaccinations  people_vaccinated  \
2059   Wales      NaN  2021-01-28            362970.0           362253.0   
2060   Wales      NaN  2021-01-29            378950.0           378200.0   
2061   Wales      NaN  2021-01-30            404249.0           403463.0   
2062   Wales      NaN  2021-01-31            417147.0           416306.0   
2063   Wales      NaN  2021-02-01            440706.0           439640.0   

      people_fully_vaccinated  daily_vaccinations_raw  daily_vaccinations  \
2059                    717.0                 26225.0             21463.0   
2060                    750.0                 15980.0             19705.0   
2061                    786.0                 25299.0             19885.0   
2062                    841.0                 12898.0             20824.0   
2063                   1066.0                 23559.0             21508.0   

      total_vaccinations_per_hundred  people_vaccinated_per_hundred  \
2059                           11.51                          11.49   
2060                           12.02                          12.00   
2061                           12.82                          12.80   
2062                           13.23                          13.20   
2063                           13.98                          13.94   

      people_fully_vaccinated_per_hundred  daily_vaccinations_per_million  \
2059                                 0.02                          6807.0   
2060                                 0.02                          6250.0   
2061                                 0.02                          6307.0   
2062                                 0.03                          6605.0   
2063                                 0.03                          6822.0   

                                 vaccines                       source_name  \
2059  Oxford/AstraZeneca, Pfizer/BioNTech  Government of the United Kingdom   
2060  Oxford/AstraZeneca, Pfizer/BioNTech  Government of the United Kingdom   
2061  Oxford/AstraZeneca, Pfizer/BioNTech  Government of the United Kingdom   
2062  Oxford/AstraZeneca, Pfizer/BioNTech  Government of the United Kingdom   
2063  Oxford/AstraZeneca, Pfizer/BioNTech  Government of the United Kingdom   

                                         source_website  
2059  https://coronavirus.data.gov.uk/details/health...  
2060  https://coronavirus.data.gov.uk/details/health...  
2061  https://coronavirus.data.gov.uk/details/health...  
2062  https://coronavirus.data.gov.uk/details/health...  
2063  https://coronavirus.data.gov.uk/details/health...

In [67]:
%%time
print(np.array([df.country]))




[['Algeria' 'Algeria' 'Andorra' ... 'Wales' 'Wales' 'Wales']]
Wall time: 4 ms


In [68]:
%%time
print(list(df.country))

['Algeria', 'Algeria', 'Andorra', 'Andorra', 'Andorra', 'Andorra', 'Andorra', 'Andorra', 'Andorra', 'Andorra', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahr

In [69]:
a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)

In [70]:
b

array([[1, 2, 3]])

In [71]:
c

array([[1],
       [2],
       [3]])

In [80]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
b=a.flatten()
c=a.ravel()

In [81]:
a[0][0]=100

In [82]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
c

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])